name: Build and Deploy

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7  # Replace with your Ruby version

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build and Deploy
      run: |
        JEKYLL_ENV=production bundle exec jekyll build
        echo 'yourdomain.com' > _site/CNAME  # Optional: If you have a custom domain

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages  # Replace with your branch name
        publish_dir: ./_site
